[package]
name = "mikui"
version = "0.1.0"
description = "Kafka Messages Viewer"
authors = ["nahua"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mikui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["clock"] }
rdkafka = { version = "0.36", features = ["ssl", "sasl"] }
tauri-plugin-dialog = "2"
