#!/usr/bin/env bash
# Штампует скриншоты дисклеймером: данные придуманы, кластера за ними нет.
#
# Как запускать (из корня репозитория; нужен только clang из Xcode CLT —
# бинарник собирается сам и кешируется в $TMPDIR):
#
#   ./demo/watermark.sh                    # весь demo/screenshots → screenshots/watermarked
#   ./demo/watermark.sh shot.png other.png # только эти файлы
#   ./demo/watermark.sh --in-place         # перезаписать исходники
#   ./demo/watermark.sh --opacity 0.03     # плитка бледнее (по умолчанию 0.055)
#   ./demo/watermark.sh --text "…" --badge "…" --tile "…"   # свои надписи
#   ./demo/watermark.sh --help             # все ключи
#
# По умолчанию берёт все png из demo/screenshots (кроме уже проштампованных) и
# кладёт результат в demo/screenshots/watermarked, не трогая исходники, — чтобы
# переснимать штамп можно было сколько угодно раз. `--in-place` перезаписывает
# файлы на месте; повторный запуск после него наложит штамп второй раз, так что
# исходники стоит где-нибудь сохранить.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source_file="$here/watermark.m"
shots="$here/screenshots"
binary="${TMPDIR:-/tmp}/mikui-watermark"

tile="SYNTHETIC DEMO DATA"
badge="NOT REAL DATA"
disclaimer="Synthetic demo data generated by AI. Nothing here comes from a real Kafka cluster."
opacity="0.055"
in_place=0
files=()

usage() {
  cat <<'TEXT'
watermark.sh — наложить дисклеймер на скриншоты

  --in-place            перезаписать исходные файлы (по умолчанию — в screenshots/watermarked)
  --opacity N           прозрачность диагональной плитки, 0..1 (по умолчанию 0.055)
  --tile ТЕКСТ          надпись плитки
  --badge ТЕКСТ         метка в левом углу полосы
  --text ТЕКСТ          сам дисклеймер в полосе
  файлы...              что штамповать (по умолчанию — весь demo/screenshots)
TEXT
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --in-place) in_place=1; shift ;;
    --opacity) opacity="$2"; shift 2 ;;
    --tile) tile="$2"; shift 2 ;;
    --badge) badge="$2"; shift 2 ;;
    --text) disclaimer="$2"; shift 2 ;;
    -h | --help) usage; exit 0 ;;
    -*) usage; echo "✗ не знаю ключ «$1»" >&2; exit 2 ;;
    *) files+=("$1"); shift ;;
  esac
done

command -v clang >/dev/null 2>&1 || {
  echo "✗ нет clang — поставь Xcode Command Line Tools: xcode-select --install" >&2
  exit 1
}

# Пересобираем только когда исходник новее собранного: штамповка пяти файлов
# иначе целиком уходила бы в компиляцию.
if [[ ! -x "$binary" || "$source_file" -nt "$binary" ]]; then
  clang -fobjc-arc -O2 \
    -framework Foundation -framework CoreGraphics -framework CoreText \
    -framework ImageIO -framework CoreServices \
    -o "$binary" "$source_file"
fi

if [[ ${#files[@]} -eq 0 ]]; then
  while IFS= read -r found; do
    files+=("$found")
  done < <(find "$shots" -maxdepth 1 -type f -name '*.png' | sort)
fi

[[ ${#files[@]} -gt 0 ]] || {
  echo "✗ нечего штамповать: в $shots нет png" >&2
  exit 1
}

if [[ $in_place -eq 0 ]]; then
  mkdir -p "$shots/watermarked"
fi

for file in "${files[@]}"; do
  name="$(basename "$file")"
  if [[ $in_place -eq 1 ]]; then
    # Через временный файл: писать в тот же путь, откуда читаем, нельзя.
    "$binary" "$file" "$file.tmp.png" "$tile" "$disclaimer" "$badge" "$opacity"
    mv "$file.tmp.png" "$file"
    echo "· $name (на месте)"
  else
    "$binary" "$file" "$shots/watermarked/$name" "$tile" "$disclaimer" "$badge" "$opacity"
    echo "· $name → watermarked/$name"
  fi
done
